---
name: DistributedDimensions
main: com.edouardcourty.dd.paper.DistributedDimensions
version: 1.0.0
api-version: 26.2
author: Edouard Courty <https://github.com/EdouardCourty>
commands:
  ddinfo:
    description: Displays information about DistributedDimensions settings.
    permission: distributeddimensions.admin
permissions:
  distributeddimensions.admin:
    description: Allows checking DD info
    default: op