name: CI & Release

on:
  push:
    branches: [ "**" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: temurin
          cache: maven

      - name: Test and Build
        run: mvn --batch-mode clean package

      - name: Upload Paper Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dd-paper
          path: dd-paper/target/dd-paper-*.jar

      - name: Upload Velocity Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dd-velocity
          path: dd-velocity/target/dd-velocity-*.jar

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dd-paper/target/dd-paper-*.jar
            dd-velocity/target/dd-velocity-*.jar
          generate_release_notes: true
